### ISSUE TITLE
ERROR ~ No such variable: manifest

### ISSUE THREAD

**Issue by kaplans1** [nf-core/chipseq#149]
Hello - I am attempting to setup the pipeline. I saw a similar issue documented some time ago, but I was unable to figure it out. Seems like it might be a machine-specific issue. Let me know if there is any other information that might be helpful.

When I try a test run:
nextflow run nf-core/chipseq -profile test singularity
I get the following error:
ERROR ~ No such variable: manifest

Some details:
Nextflow - version 0.25.6 build 4526
singularity version 2.4.2 (tried with 2.6, but got the same error)
java version 1.8.0_172

This is the tail end of the log file (let me know if you need the beginning part):
Apr-11 15:29:49.045 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Apr-11 15:29:49.754 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-11 15:29:49.810 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: manifest for class: nextflow.script.WorkflowMetadata
Apr-11 15:29:49.827 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: manifest for class: nextflow.script.WorkflowMetadata
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at _nf_script_42d7b5ce.nfcoreHeader(_nf_script_42d7b5ce:1665)
	at _nf_script_42d7b5ce.run(_nf_script_42d7b5ce:208)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:325)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:156)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:223)
	at nextflow.cli.Launcher.run(Launcher.groovy:410)
	at nextflow.cli.Launcher.main(Launcher.groovy:564)

**Comment by drpatelh** [comment]
Hi @kaplans1! You are using a very old version of Nextflow in which the `manifest` feature wasn't added yet :wink: Please update to the latest version and hopefully things will be better behaved. I'll close this for now but feel free to reopen or join the #chipseq channel on the nf-core Slack workspace if you have any more issues.

**Comment by drpatelh** [comment]
Just spotted need a comma between the profiles too and not a space:
`nextflow run nf-core/chipseq -profile test,singularity`

**Comment by kaplans1** [comment]
Perfect - upgrading nextflow and properly formatting the command resolved the issue. Thank you!

**Comment by drpatelh** [comment]
Great!
