### ISSUE TITLE
Access deny error using singu

### ISSUE THREAD

**Issue by shangl02** [nf-core/chipseq#245]
Hi, I pulled the latest pipeline, and run it with
`nextflow run nf-core/chipseq -c ChIPSeq_custom.config -profile conda --input /hpc/grid/wip_drm_targetsciences/projects/p046_KDM5/ChIPSeq.01112022/KDM5_ChIPSeq.design.csv --genome GRCh38 --outdir /hpc/grid/wip_drm_targetsciences/projects/p046_KDM5/ChIPSeq.01112022/nextflow.result/`

Error pops after a few seconds
```
"Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: X4NM8S9XW39JDWS0; S3 Extended Request ID: I2SUzxr0yJ21/ggT6DkQvr2zERm/T721ccGlSJlxc+x8n+i7t+jrd7qkCgrpqIsrb3p+ICBlcx8=)

 -- Check script '/home/shangl02/.nextflow/assets/nf-core/chipseq/main.nf' at line: 171 or see '.nextflow.log' file for more details"
```

Details in .nextflow.log 
```
Jan-26 13:09:56.850 [main] DEBUG nextflow.Session - Session aborted -- Cause: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: X4NM8S9XW39JDWS0;
 S3 Extended Request ID: I2SUzxr0yJ21/ggT6DkQvr2zERm/T721ccGlSJlxc+x8n+i7t+jrd7qkCgrpqIsrb3p+ICBlcx8=)
Jan-26 13:09:56.873 [main] ERROR nextflow.cli.Launcher - @unknown
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: X4NM8S9XW39JDWS0; S3 Extended Request ID: I2
SUzxr0yJ21/ggT6DkQvr2zERm/T721ccGlSJlxc+x8n+i7t+jrd7qkCgrpqIsrb3p+ICBlcx8=)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4854)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:880)
        at com.upplication.s3fs.AmazonS3Client.listObjects(AmazonS3Client.java:104)
        at com.upplication.s3fs.util.S3ObjectSummaryLookup.lookup(S3ObjectSummaryLookup.java:116)
        at com.upplication.s3fs.S3FileSystemProvider.getAccessControl(S3FileSystemProvider.java:894)
        at com.upplication.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:588)
        at java.nio.file.Files.exists(Files.java:2385)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:94)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at nextflow.extension.FilesEx.exists(FilesEx.groovy:453)
        at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:971)
        at nextflow.file.FileHelper$checkIfExists$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at nextflow.file.FileHelper$checkIfExists$2.call(Unknown Source)
        at nextflow.Nextflow.file(Nextflow.groovy:158)
        at nextflow.Nextflow$file.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)
        at Script_cc06130a.runScript(Script_cc06130a:171)
        at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:153)
        at nextflow.script.BaseScript.run(BaseScript.groovy:189)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:225)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:273)
        at nextflow.cli.Launcher.run(Launcher.groovy:460)
        at nextflow.cli.Launcher.main(Launcher.groovy:642)
```

**Comment by JoseEspinosa** [comment]
Yep, this came up before on the nf-core slack channel. I would guess that you probably have your AWS credentials in your home directory and nextflow tries to use them. The error source of the error is that your credentials point to a different AWS region than were AWS iGenomes is hosted (eu-west-1). The solution is to move your credentials somewhere else temporarily or rename them.

**Comment by JoseEspinosa** [comment]
I will close this issue since it has been inactive for a long time. Let us know if you have any other issues.
